version: 0.2

phases:
  build:
    commands:
      - echo "🚀 Starting multi-repo build test!"
      - echo "🔍 DockerSourceOutput (this repo) contents:"
      - ls -la .

      - echo "🔍 AppSourceOutput contents at \$CODEBUILD_SRC_DIR_AppSourceOutput:"
      - ls -la "$CODEBUILD_SRC_DIR_AppSourceOutput" || echo "❌ AppSourceOutput not found"

      - echo "✅ Check for test file in app repo:"
      - test -f "$CODEBUILD_SRC_DIR_AppSourceOutput/README.md" && echo "✅ README.md found in app repo" || echo "❌ README.md missing in app repo"

